Capstone Project: Conference page
sanieni6/Module_1-Capstone-project pull request #1
Opened 2023-02-08 22:56 UTC by sanieni6

## First capstone Project: Conference Page (Quevedo Fest)
This is the first capstone project of the Microverve program corresponding to module one. 
This project was divided into three days of work:
### Day 1: 
+ Set up the repository and tools.  ✔️ 
+ Choose the topic and the resources for the project ✔️ 
+ Crete the mobile version ✔️ 
### Day 2:
+ Create the desktop version. ✔️ 
+ Implement the user interactions: link, mobile menu ✔️ 
### Day 3:
+ Implement the section "Featured speakers" with dynamic HTML. ✔️ 
+ Deploy the project ✔️ 
+ Record a video describing your project. ✔️

2023-02-08 23:48 UTC, m05e5 requested changes
Hi @sanieni6 , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] As part of the best practices and to improve SEO ill recommend adding a `h1` tag you your app.
- [ ] Please check the comments below 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 23:48 UTC, m05e5 commented on index.html
> +
- [ ] Hi. As part of the requirement you are supposed to follow the provided design as much as possible so please try considering the below change suggestions
- The partner section should only be present on the home page not on the about page
- The footer on the about page is black. Please consider changing the color

**Provided design**
<img width="862" alt="image" src="https://user-images.githubusercontent.com/37901469/217676950-dfc3e20a-b24a-4538-9f1f-91948fc54670.png">


**your UI**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37901469/217677036-ed9aad0a-9335-4704-bfa8-a61822a0fa91.png">

2023-02-09 03:53 UTC, sanieni6 commented
## Required changes done.
These were the changes done to the project:
+ Present the partner section just on the home page, not on the about page.*****
+ Change the color of the footer

****As part of the requirements in the Behance template, the partner section is not shown just in the about for the desktop version. It means the partner section will show in the about of the mobile version as you can see in the attached image.
![image](https://user-images.githubusercontent.com/64999622/217713443-55e0b505-5e89-4a10-95e4-5b9478eca7f2.png)

2023-02-09 04:22 UTC, Tadesse-Alemayehu approved these changes
### Hi @sanieni6 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
 - [ ]  Correct GitHub Flow. ✅
 - [ ]  Good commit history. ✅
 - [ ]  Good PR title/description. ✅
 - [ ]  All linters passed ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 13:50 UTC, merged